# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='native_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.LanguageModel'),
        ),
    ]
