# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 11:57
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180504_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseUserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('achieved_score', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'tbl_exercise_user',
            },
        ),
        migrations.AddField(
            model_name='exercisemodel',
            name='media',
            field=models.IntegerField(choices=[(0, 'Textual question'), (1, 'Audio type question'), (2, 'Video type question')], default=0),
        ),
        migrations.AddField(
            model_name='exercisemodel',
            name='nature',
            field=models.IntegerField(choices=[(0, 'Grammar focused exercise'), (1, 'Vocabulary focused exercise'), (2, 'Spelling focused exercise'), (3, 'Other type of exercise')], default=0),
        ),
        migrations.AddField(
            model_name='exercisemodel',
            name='pauses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, help_text='Time points in it, that specify when to display a question, if the media is a video', null=True, size=None),
        ),
        migrations.AddField(
            model_name='exercisemodel',
            name='url_question',
            field=models.URLField(blank=True, help_text='If user provides a link to an audio or video file', null=True),
        ),
        migrations.AlterField(
            model_name='exercisemodel',
            name='conjunction',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), help_text='Connection between questions and answers', size=None),
        ),
        migrations.AddField(
            model_name='exerciseusermodel',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ExerciseModel'),
        ),
        migrations.AddField(
            model_name='exerciseusermodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
