# Generated by Django 3.0 on 2020-02-25 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200103_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercisemodel',
            old_name='url_question',
            new_name='material_url',
        ),
        migrations.RemoveField(
            model_name='exercisemodel',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='exercisemodel',
            name='conjunction',
        ),
        migrations.RemoveField(
            model_name='exercisemodel',
            name='max_score',
        ),
        migrations.RemoveField(
            model_name='exercisemodel',
            name='pauses',
        ),
        migrations.RemoveField(
            model_name='exercisemodel',
            name='questions',
        ),
        migrations.AlterModelTable(
            name='exercisemodel',
            table='tbl_exercises',
        ),
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('time_point', models.FloatField(blank=True, null=True)),
                ('max_score', models.PositiveSmallIntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='api.ExerciseModel')),
            ],
            options={
                'db_table': 'tbl_questions',
            },
        ),
        migrations.CreateModel(
            name='AnswerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=400)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='api.QuestionModel')),
            ],
            options={
                'db_table': 'tbl_answers',
            },
        ),
    ]
